# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.runs/synth_1/Wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 2
set_param general.usePosixSpawnForFork 1
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.cache/wt} [current_project]
set_property parent.project_path {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/mem_files/typewriter.mem}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/mem_files/hw_master_test.mem}
}
read_verilog -library xil_defaultlib {
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/PC.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/PWMSerializer.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/RAM.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/ROM.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/RSRTRD.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/ServoController.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/alu.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/anandgate.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/annotb.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/anorgate.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/cla8bit.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/clock_div.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/counter.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/dffe_ref.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/hardware_master.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/keyboard_input.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/multdiv.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/mux2.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/mux2_33.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/mux2onebit.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/mux4.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/mux4_33.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/mux8.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/mux8_33.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/one_reg.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/onetwentyeightbit_reg.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/pen_driver.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/poll_keyboard_tb.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/processor.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/ps2_keyboard_sampler.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/ps2_rx.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/regfile.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/sixtyfourbit_reg.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/sixtysixbit_reg.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/sll.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/sra.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/stepper_driver.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/tffe.v}
  {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/imports/proc/Wrapper.v}
}
read_ip -quiet {{C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/ip/CPU_clock/CPU_clock.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.gen/sources_1/ip/CPU_clock/CPU_clock_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.gen/sources_1/ip/CPU_clock/CPU_clock.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.gen/sources_1/ip/CPU_clock/CPU_clock_ooc.xdc}}]

read_ip -quiet {{C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/ip/pen_clock/pen_clock.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.gen/sources_1/ip/pen_clock/pen_clock_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.gen/sources_1/ip/pen_clock/pen_clock.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.gen/sources_1/ip/pen_clock/pen_clock_ooc.xdc}}]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/constrs_1/imports/proc/master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/constrs_1/imports/proc/master.xdc}}]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental {C:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/utils_1/imports/synth_1/Wrapper.dcp}
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Wrapper -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file Wrapper_utilization_synth.rpt -pb Wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
