# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/ip/pen_clock/pen_clock.xci
# IP: The module: 'pen_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.gen/sources_1/ip/pen_clock/pen_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pen_clock'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.gen/sources_1/ip/pen_clock/pen_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'pen_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.gen/sources_1/ip/pen_clock/pen_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pen_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.srcs/sources_1/ip/pen_clock/pen_clock.xci
# IP: The module: 'pen_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.gen/sources_1/ip/pen_clock/pen_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pen_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.gen/sources_1/ip/pen_clock/pen_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'pen_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/whale/Documents/ECE350/Vivado Projects/ece350-final-project/Project.gen/sources_1/ip/pen_clock/pen_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pen_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
